"""Initial schema after manual migration

Revision ID: f277cb5f7c69
Revises: e6bc7c6a08b5
Create Date: 2025-11-08 17:57:00.990967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f277cb5f7c69'
down_revision = 'e6bc7c6a08b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
