"""Add forecast table + order_lines.forecast meta

Revision ID: 1743593a6a5b
Revises: f835c7b8f21c
Create Date: 2025-11-02 15:30:55.155642

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1743593a6a5b"
down_revision = "f835c7b8f21c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "forecast",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("forecast_id", sa.String(length=36), nullable=False),
        sa.Column("product_id", sa.String(length=64), nullable=False),
        sa.Column("client_id", sa.String(length=64), nullable=False),
        sa.Column("supplier_id", sa.String(length=64), nullable=False),
        sa.Column("granularity", sa.String(length=16), nullable=False),
        sa.Column("date_day", sa.Date(), nullable=True),
        sa.Column("date_dekad_start", sa.Date(), nullable=True),
        sa.Column("year_month", sa.String(length=7), nullable=True),
        sa.Column("qty_forecast", sa.Integer(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("version_issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_system", sa.String(length=32), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "( (granularity='daily'   AND date_day IS NOT NULL     AND date_dekad_start IS NULL AND year_month IS NULL) OR  (granularity='dekad'   AND date_dekad_start IS NOT NULL AND date_day IS NULL     AND year_month IS NULL) OR  (granularity='monthly' AND year_month IS NOT NULL   AND date_day IS NULL         AND date_dekad_start IS NULL))",
            name="ck_forecast_period_key_exclusivity",
        ),
        sa.CheckConstraint(
            "granularity in ('daily','dekad','monthly')", name="ck_forecast_granularity"
        ),
        sa.CheckConstraint("qty_forecast >= 0", name="ck_forecast_qty_nonneg"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("forecast_id"),
    )
    with op.batch_alter_table("order_lines") as batch_op:
        batch_op.add_column(sa.Column("forecast_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("forecast_granularity", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column("forecast_match_status", sa.Text(), nullable=True)
        )
        batch_op.add_column(sa.Column("forecast_qty", sa.Float(), nullable=True))
        batch_op.add_column(
            sa.Column("forecast_version_no", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            "fk_order_lines_forecast",  # ← 明示的な名前にする
            "forecast",  # 参照先テーブル
            ["forecast_id"],  # 子
            ["id"],  # 親
        )


def downgrade():
    # 逆順で安全に戻す（こちらもバッチで）
    with op.batch_alter_table("order_lines") as batch_op:
        batch_op.drop_constraint("fk_order_lines_forecast", type_="foreignkey")
        batch_op.drop_column("forecast_version_no")
        batch_op.drop_column("forecast_qty")
        batch_op.drop_column("forecast_match_status")
        batch_op.drop_column("forecast_granularity")
        batch_op.drop_column("forecast_id")

    op.drop_table("forecast")
