"""Initial schema from models

Revision ID: f835c7b8f21c
Revises: 
Create Date: 2025-11-02 14:27:02.712118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f835c7b8f21c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_code', sa.Text(), nullable=False),
    sa.Column('customer_name', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('customer_code')
    )
    op.create_table('ocr_submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.Text(), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('operator', sa.Text(), nullable=True),
    sa.Column('schema_version', sa.Text(), nullable=True),
    sa.Column('target_type', sa.Text(), nullable=True),
    sa.Column('submission_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.Column('processed_records', sa.Integer(), nullable=True),
    sa.Column('failed_records', sa.Integer(), nullable=True),
    sa.Column('skipped_records', sa.Integer(), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id')
    )
    op.create_table('products',
    sa.Column('product_code', sa.Text(), nullable=False),
    sa.Column('product_name', sa.Text(), nullable=False),
    sa.Column('customer_part_no', sa.Text(), nullable=True),
    sa.Column('maker_part_no', sa.Text(), nullable=True),
    sa.Column('internal_unit', sa.Text(), nullable=False),
    sa.Column('packaging', sa.Text(), nullable=True),
    sa.Column('assemble_div', sa.Text(), nullable=True),
    sa.Column('next_div', sa.Text(), nullable=True),
    sa.Column('shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('requires_lot_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('product_code')
    )
    op.create_table('suppliers',
    sa.Column('supplier_code', sa.Text(), nullable=False),
    sa.Column('supplier_name', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('supplier_code')
    )
    op.create_table('warehouses',
    sa.Column('warehouse_code', sa.Text(), nullable=False),
    sa.Column('warehouse_name', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('warehouse_code')
    )
    op.create_table('expiry_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_code', sa.Text(), nullable=True),
    sa.Column('supplier_code', sa.Text(), nullable=True),
    sa.Column('rule_type', sa.Text(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.Column('fixed_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_code'], ['products.product_code'], ),
    sa.ForeignKeyConstraint(['supplier_code'], ['suppliers.supplier_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_code', sa.Text(), nullable=False),
    sa.Column('product_code', sa.Text(), nullable=False),
    sa.Column('lot_number', sa.Text(), nullable=False),
    sa.Column('receipt_date', sa.Date(), nullable=False),
    sa.Column('mfg_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('warehouse_code', sa.Text(), nullable=True),
    sa.Column('kanban_class', sa.Text(), nullable=True),
    sa.Column('sales_unit', sa.Text(), nullable=True),
    sa.Column('inventory_unit', sa.Text(), nullable=True),
    sa.Column('received_by', sa.Text(), nullable=True),
    sa.Column('source_doc', sa.Text(), nullable=True),
    sa.Column('qc_certificate_status', sa.Text(), nullable=True),
    sa.Column('qc_certificate_file', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_code'], ['products.product_code'], ),
    sa.ForeignKeyConstraint(['supplier_code'], ['suppliers.supplier_code'], ),
    sa.ForeignKeyConstraint(['warehouse_code'], ['warehouses.warehouse_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_code', 'product_code', 'lot_number', name='uq_lot_supplier_product_no')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_no', sa.Text(), nullable=False),
    sa.Column('customer_code', sa.Text(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('sap_order_id', sa.Text(), nullable=True),
    sa.Column('sap_status', sa.Text(), nullable=True),
    sa.Column('sap_sent_at', sa.DateTime(), nullable=True),
    sa.Column('sap_error_msg', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_code'], ['customers.customer_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    op.create_table('product_uom_conversions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_code', sa.Text(), nullable=False),
    sa.Column('source_unit', sa.Text(), nullable=False),
    sa.Column('source_value', sa.Float(), nullable=False),
    sa.Column('internal_unit_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_code'], ['products.product_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_code', 'source_unit', name='uq_product_unit')
    )
    op.create_table('receipt_headers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('receipt_no', sa.Text(), nullable=True),
    sa.Column('supplier_code', sa.Text(), nullable=False),
    sa.Column('warehouse_code', sa.Text(), nullable=False),
    sa.Column('receipt_date', sa.Date(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_code'], ['suppliers.supplier_code'], ),
    sa.ForeignKeyConstraint(['warehouse_code'], ['warehouses.warehouse_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_no')
    )
    op.create_table('lot_current_stock',
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('current_quantity', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lot_id')
    )
    op.create_table('order_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_code'], ['products.product_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'line_no', name='uq_order_line')
    )
    op.create_table('receipt_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('header_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.Text(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['header_id'], ['receipt_headers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['product_code'], ['products.product_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('header_id', 'line_no', name='uq_receipt_header_line')
    )
    op.create_table('sap_sync_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('related_id', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stock_movements_lot', 'stock_movements', ['lot_id'], unique=False)
    op.create_table('allocations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_line_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('allocated_qty', sa.Float(), nullable=False),
    sa.Column('allocated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_line_id'], ['order_lines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alloc_lot', 'allocations', ['lot_id'], unique=False)
    op.create_index('ix_alloc_ol', 'allocations', ['order_line_id'], unique=False)
    op.create_table('purchase_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_code', sa.Text(), nullable=False),
    sa.Column('supplier_code', sa.Text(), nullable=False),
    sa.Column('requested_qty', sa.Float(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('reason_code', sa.Text(), nullable=False),
    sa.Column('src_order_line_id', sa.Integer(), nullable=True),
    sa.Column('requested_date', sa.Date(), nullable=True),
    sa.Column('desired_receipt_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('sap_po_id', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_code'], ['products.product_code'], ),
    sa.ForeignKeyConstraint(['src_order_line_id'], ['order_lines.id'], ),
    sa.ForeignKeyConstraint(['supplier_code'], ['suppliers.supplier_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipping',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('order_line_id', sa.Integer(), nullable=True),
    sa.Column('shipped_quantity', sa.Float(), nullable=False),
    sa.Column('shipping_date', sa.Date(), nullable=False),
    sa.Column('destination_code', sa.Text(), nullable=True),
    sa.Column('destination_name', sa.Text(), nullable=True),
    sa.Column('destination_address', sa.Text(), nullable=True),
    sa.Column('contact_person', sa.Text(), nullable=True),
    sa.Column('contact_phone', sa.Text(), nullable=True),
    sa.Column('delivery_time_slot', sa.Text(), nullable=True),
    sa.Column('tracking_number', sa.Text(), nullable=True),
    sa.Column('carrier', sa.Text(), nullable=True),
    sa.Column('carrier_service', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['order_line_id'], ['order_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipping')
    op.drop_table('purchase_requests')
    op.drop_index('ix_alloc_ol', table_name='allocations')
    op.drop_index('ix_alloc_lot', table_name='allocations')
    op.drop_table('allocations')
    op.drop_index('ix_stock_movements_lot', table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_table('sap_sync_logs')
    op.drop_table('receipt_lines')
    op.drop_table('order_lines')
    op.drop_table('lot_current_stock')
    op.drop_table('receipt_headers')
    op.drop_table('product_uom_conversions')
    op.drop_table('orders')
    op.drop_table('lots')
    op.drop_table('expiry_rules')
    op.drop_table('warehouses')
    op.drop_table('suppliers')
    op.drop_table('products')
    op.drop_table('ocr_submissions')
    op.drop_table('customers')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
