# backend/app/schemas/__init__.py
"""Unified re-export of schema classes."""

from __future__ import annotations

from .admin import (
    AdminPresetListResponse,
    AdminPresetLoadResponse,
    DashboardStatsResponse,
    FullSampleDataRequest,
)

from .allocations import (
    DragAssignRequest,
    DragAssignResponse,
    FefoCommitResponse,
    FefoLineAllocation,
    FefoLotAllocation,
    FefoPreviewRequest,
    FefoPreviewResponse,
)

from .base import (
    BaseSchema,
    ResponseBase,
    TimestampMixin,
)

from .forecast import (
    ForecastActivateRequest,
    ForecastActivateResponse,
    ForecastBase,
    ForecastBulkImportRequest,
    ForecastBulkImportResponse,
    ForecastCreate,
    ForecastItemOut,
    ForecastListResponse,
    ForecastMatchRequest,
    ForecastMatchResponse,
    ForecastMatchResult,
    ForecastResponse,
    ForecastUpdate,
    ForecastVersionInfo,
    ForecastVersionListResponse,
)

from .integration import (
    OcrOrderRecord,
    OcrSubmissionRequest,
    OcrSubmissionResponse,
    SapRegisterOptions,
    SapRegisterRequest,
    SapRegisterResponse,
    SapRegisterTarget,
    SapSyncLogResponse,
)

from .inventory import (
    ExpiryRuleBase,
    ExpiryRuleCreate,
    ExpiryRuleResponse,
    ExpiryRuleUpdate,
    LotBase,
    LotCreate,
    LotCurrentStockResponse,
    LotResponse,
    LotUpdate,
    ReceiptCreateRequest,
    ReceiptHeaderBase,
    ReceiptHeaderCreate,
    ReceiptHeaderResponse,
    ReceiptLineBase,
    ReceiptLineCreate,
    ReceiptLineResponse,
    ReceiptResponse,
    StockMovementBase,
    StockMovementCreate,
    StockMovementResponse,
)

from .masters import (
    CustomerBase,
    CustomerCreate,
    CustomerResponse,
    CustomerUpdate,
    MasterBulkLoadRequest,
    MasterBulkLoadResponse,
    ProductBase,
    ProductCreate,
    ProductResponse,
    ProductUomConversionBase,
    ProductUomConversionCreate,
    ProductUomConversionResponse,
    ProductUomConversionUpdate,
    ProductUpdate,
    SupplierBase,
    SupplierCreate,
    SupplierResponse,
    SupplierUpdate,
    WarehouseBase,
    WarehouseCreate,
    WarehouseResponse,
    WarehouseUpdate,
)

from .orders import (
    AllocationWarning,
    LotCandidateListResponse,
    LotCandidateOut,
    OrderBase,
    OrderCreate,
    OrderLineBase,
    OrderLineCreate,
    OrderLineOut,
    OrderLineResponse,
    OrderResponse,
    OrderStatusUpdate,
    OrderUpdate,
    OrderValidationDetails,  # ← 追加
    OrderValidationErrorData,
    OrderValidationLotAvailability,
    OrderValidationRequest,
    OrderValidationResponse,
    OrderWithLinesResponse,
    OrdersWithAllocResponse,
    SaveAllocationsRequest,
    WarehouseAllocIn,
    WarehouseAllocOut,
)

from .warehouses import (
    WarehouseListResponse,
    WarehouseOut,
)

__all__ = [
    "AdminPresetListResponse",
    "AdminPresetLoadResponse",
    "AllocationWarning",
    "BaseSchema",
    "CustomerBase",
    "CustomerCreate",
    "CustomerResponse",
    "CustomerUpdate",
    "DashboardStatsResponse",
    "DragAssignRequest",
    "DragAssignResponse",
    "ExpiryRuleBase",
    "ExpiryRuleCreate",
    "ExpiryRuleResponse",
    "ExpiryRuleUpdate",
    "FefoCommitResponse",
    "FefoLineAllocation",
    "FefoLotAllocation",
    "FefoPreviewRequest",
    "FefoPreviewResponse",
    "ForecastActivateRequest",
    "ForecastActivateResponse",
    "ForecastBase",
    "ForecastBulkImportRequest",
    "ForecastBulkImportResponse",
    "ForecastCreate",
    "ForecastItemOut",
    "ForecastListResponse",
    "ForecastMatchRequest",
    "ForecastMatchResponse",
    "ForecastMatchResult",
    "ForecastResponse",
    "ForecastUpdate",
    "ForecastVersionInfo",
    "ForecastVersionListResponse",
    "FullSampleDataRequest",
    "LotBase",
    "LotCandidateListResponse",
    "LotCandidateOut",
    "LotCreate",
    "LotCurrentStockResponse",
    "LotResponse",
    "LotUpdate",
    "MasterBulkLoadRequest",
    "MasterBulkLoadResponse",
    "OcrOrderRecord",
    "OcrSubmissionRequest",
    "OcrSubmissionResponse",
    "OrderBase",
    "OrderCreate",
    "OrderLineBase",
    "OrderLineCreate",
    "OrderLineOut",
    "OrderLineResponse",
    "OrderResponse",
    "OrderStatusUpdate",
    "OrderUpdate",
    "OrderValidationDetails",  # ← 追加
    "OrderValidationErrorData",
    "OrderValidationLotAvailability",
    "OrderValidationRequest",
    "OrderValidationResponse",
    "OrderWithLinesResponse",
    "OrdersWithAllocResponse",
    "ProductBase",
    "ProductCreate",
    "ProductResponse",
    "ProductUomConversionBase",
    "ProductUomConversionCreate",
    "ProductUomConversionResponse",
    "ProductUomConversionUpdate",
    "ProductUpdate",
    "ReceiptCreateRequest",
    "ReceiptHeaderBase",
    "ReceiptHeaderCreate",
    "ReceiptHeaderResponse",
    "ReceiptLineBase",
    "ReceiptLineCreate",
    "ReceiptLineResponse",
    "ReceiptResponse",
    "ResponseBase",
    "SapRegisterOptions",
    "SapRegisterRequest",
    "SapRegisterResponse",
    "SapRegisterTarget",
    "SapSyncLogResponse",
    "SaveAllocationsRequest",
    "StockMovementBase",
    "StockMovementCreate",
    "StockMovementResponse",
    "SupplierBase",
    "SupplierCreate",
    "SupplierResponse",
    "SupplierUpdate",
    "TimestampMixin",
    "WarehouseAllocIn",
    "WarehouseAllocOut",
    "WarehouseBase",
    "WarehouseCreate",
    "WarehouseListResponse",
    "WarehouseOut",
    "WarehouseResponse",
    "WarehouseUpdate",
]