from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any
import uuid

import pandas as pd
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.table import Table, TableStyleInfo


# プロジェクトルートを基準にしたパス
PROJECT_ROOT = Path(__file__).resolve().parents[1]
SCHEMA_SQL = PROJECT_ROOT / "docs" / "schema" / "03_db_schema_current.sql"
OPENAPI_JSON = PROJECT_ROOT / "docs" / "schema" / "current_openapi.json"
OUTPUT_XLSX = PROJECT_ROOT / "docs" / "schema" / "api_db_matrix.xlsx"


@dataclass
class ColumnDef:
    table_name: str
    column_name: str
    data_type: str
    is_primary_key: bool = False
    foreign_key: str | None = None
    raw_line: str = ""


@dataclass
class EndpointDef:
    path: str
    method: str
    summary: str
    tags: str
    operation_id: str


def parse_schema_sql(path: Path) -> list[ColumnDef]:
    """
    docs/schema/03_db_schema_current.sql から
    テーブルとカラム定義 + PK/FK を抜き出す。
    """
    text = path.read_text(encoding="utf-8")

    # CREATE TABLE ... (...) をテーブル単位で抜き出す
    table_blocks = re.split(r"(?i)\bCREATE\s+TABLE\b", text)

    results: list[ColumnDef] = []

    for block in table_blocks[1:]:
        header_and_body = block.split("(", 1)
        if len(header_and_body) != 2:
            continue

        header, body = header_and_body
        # public.orders や orders を拾う
        m_table = re.search(r"(?P<name>(?:\w+\.)?\w+)", header.strip())
        if not m_table:
            continue

        full_table_name = m_table.group("name")
        table_name = full_table_name.split(".")[-1]

        body_before_close = re.split(r"\);\s*", body, 1)[0]
        lines = [ln.rstrip() for ln in body_before_close.splitlines()]

        # 1パス目: カラム定義
        columns_by_name: dict[str, ColumnDef] = {}
        column_order: list[str] = []

        for line in lines:
            line_stripped = line.strip()
            if not line_stripped:
                continue

            upper = line_stripped.upper()
            if upper.startswith(("CONSTRAINT", "PRIMARY KEY", "UNIQUE", "FOREIGN KEY", "CHECK")):
                # 制約行は別で処理
                continue

            # 例: id bigint GENERATED BY DEFAULT AS IDENTITY,
            m_col = re.match(
                r'^"?(?P<col>\w+)"?\s+(?P<type>[^,]+?)(?:,)?$',
                line_stripped,
            )
            if not m_col:
                continue

            col_name = m_col.group("col")
            data_type = m_col.group("type").strip()

            col_def = ColumnDef(
                table_name=table_name,
                column_name=col_name,
                data_type=data_type,
                raw_line=line_stripped,
            )
            columns_by_name[col_name] = col_def
            column_order.append(col_name)

        # 2パス目: 制約行から PK/FK を抽出
        for line in lines:
            line_stripped = line.strip()
            if not line_stripped:
                continue

            upper = line_stripped.upper()
            if "PRIMARY KEY" in upper:
                m_pk = re.search(r"PRIMARY\s+KEY\s*\((?P<cols>[^)]+)\)", line_stripped, re.IGNORECASE)
                if m_pk:
                    cols = [c.strip().strip('"') for c in m_pk.group("cols").split(",")]
                    for col in cols:
                        if col in columns_by_name:
                            columns_by_name[col].is_primary_key = True

            if "FOREIGN KEY" in upper and "REFERENCES" in upper:
                m_fk = re.search(
                    r"FOREIGN\s+KEY\s*\((?P<cols>[^)]+)\)\s*REFERENCES\s+(?P<reftable>[\w\.]+)\s*\((?P<refcols>[^)]+)\)",
                    line_stripped,
                    re.IGNORECASE,
                )
                if m_fk:
                    local_cols = [c.strip().strip('"') for c in m_fk.group("cols").split(",")]
                    ref_table = m_fk.group("reftable").split(".")[-1]
                    ref_cols = [c.strip().strip('"') for c in m_fk.group("refcols").split(",")]

                    # 単一 or 同数列対応（それ以上は雑に1:1対応）
                    for idx, local_col in enumerate(local_cols):
                        if local_col not in columns_by_name:
                            continue
                        ref_col = ref_cols[min(idx, len(ref_cols) - 1)]
                        columns_by_name[local_col].foreign_key = f"{ref_table}.{ref_col}"

        # カラム順で results に追加
        for col_name in column_order:
            results.append(columns_by_name[col_name])

    return results


def parse_openapi(path: Path) -> list[EndpointDef]:
    """
    OpenAPI JSON からエンドポイント一覧を取り出す。
    """
    spec: dict[str, Any] = json.loads(path.read_text(encoding="utf-8"))

    endpoints: list[EndpointDef] = []

    for path_str, methods in spec.get("paths", {}).items():
        if not isinstance(methods, dict):
            continue
        for method, op in methods.items():
            if not isinstance(op, dict):
                continue

            summary = op.get("summary", "") or ""
            tags_list = op.get("tags", []) or []
            tags = ", ".join(tags_list)
            operation_id = op.get("operationId", "") or ""

            endpoints.append(
                EndpointDef(
                    path=path_str,
                    method=method.upper(),
                    summary=summary,
                    tags=tags,
                    operation_id=operation_id,
                )
            )

    return endpoints


def build_table_api_matrix(
    columns: list[ColumnDef], endpoints: list[EndpointDef]
) -> pd.DataFrame:
    """
    テーブルごとに「API あり/なし」と、
    関連しそうなエンドポイント一覧を作成。
    """
    table_names = sorted({c.table_name for c in columns})
    rows: list[dict[str, Any]] = []

    for table in table_names:
        keyword = f"/{table}"
        related = [
            f"{ep.method} {ep.path}"
            for ep in endpoints
            if keyword in ep.path
        ]
        rows.append(
            {
                "table_name": table,
                "has_api": bool(related),
                "related_endpoints": "\n".join(sorted(set(related))),
            }
        )

    df = pd.DataFrame(rows)
    # True/False -> ○/× に変換
    df["has_api"] = df["has_api"].map(lambda v: "○" if v else "×")
    return df


def make_sheet_name(table_name: str) -> str:
    """Excel シート名用に安全な名前を作る（31文字制限対応）。"""
    base = f"tbl_{table_name}"
    # / \ ? * [ ] などを避ける
    safe = re.sub(r"[][*/?:\\]", "_", base)
    return safe[:31]


def add_excel_table(ws, style_name: str) -> None:
    """シート全体を Excel のテーブル化し、テーブル名はランダムサフィックスで一意にする"""
    if ws.max_row < 1 or ws.max_column < 1:
        return

    ref = f"A1:{get_column_letter(ws.max_column)}{ws.max_row}"

    # 基本のテーブル名（シート名ベース）
    base_name = "tbl_" + re.sub(r"[^0-9A-Za-z_]", "_", ws.title)
    base_name = base_name[:20]  # 少し短めにしておく

    # ランダムサフィックスを付けてほぼ確実に一意にする
    suffix = uuid.uuid4().hex[:6]
    table_name = f"{base_name}_{suffix}"

    table = Table(displayName=table_name, ref=ref)

    style = TableStyleInfo(
        name=style_name,
        showFirstColumn=False,
        showLastColumn=False,
        showRowStripes=True,
        showColumnStripes=False,
    )
    table.tableStyleInfo = style
    ws.add_table(table)




def main() -> None:
    # 既存ファイル削除
    if OUTPUT_XLSX.exists():
        try:
            OUTPUT_XLSX.unlink()
            print(f"🗑️ Removed existing file: {OUTPUT_XLSX}")
        except Exception:
            raise SystemExit(
                f"❌ Cannot delete existing file: {OUTPUT_XLSX}\n"
                f"Excel で開きっぱなしの可能性があります。閉じて再実行してください。"
            )
    if not SCHEMA_SQL.exists():
        raise SystemExit(f"Schema SQL not found: {SCHEMA_SQL}")

    if not OPENAPI_JSON.exists():
        raise SystemExit(
            f"OpenAPI JSON not found: {OPENAPI_JSON}\n"
            "先に backend ディレクトリで:\n"
            "  python openapi_diff_check.py generate ../docs/schema/current_openapi.json\n"
            "を実行してください。"
        )

    print(f"📄 Loading schema SQL: {SCHEMA_SQL}")
    columns = parse_schema_sql(SCHEMA_SQL)
    print(f"  -> {len({c.table_name for c in columns})} tables, {len(columns)} columns")

    print(f"📄 Loading OpenAPI JSON: {OPENAPI_JSON}")
    endpoints = parse_openapi(OPENAPI_JSON)
    print(f"  -> {len(endpoints)} endpoints")

    # ----- DataFrame 生成 -----
    df_tables = pd.DataFrame(
        [
            {
                "table_name": c.table_name,
                "column_name": c.column_name,
                "data_type": c.data_type,
                "is_primary_key": c.is_primary_key,
                "foreign_key": c.foreign_key or "",
                "raw_line": c.raw_line,
            }
            for c in columns
        ]
    ).sort_values(["table_name", "column_name"])

    df_endpoints = pd.DataFrame(
        [
            {
                "path": ep.path,
                "method": ep.method,
                "summary": ep.summary,
                "tags": ep.tags,
                "operation_id": ep.operation_id,
            }
            for ep in endpoints
        ]
    ).sort_values(["path", "method"])

    df_matrix = build_table_api_matrix(columns, endpoints)

    # ----- Excel 出力 -----
    OUTPUT_XLSX.parent.mkdir(parents=True, exist_ok=True)
    with pd.ExcelWriter(OUTPUT_XLSX, engine="openpyxl") as writer:
        # 全テーブル一覧シート
        df_tables.to_excel(writer, sheet_name="tables_all", index=False)
        df_endpoints.to_excel(writer, sheet_name="endpoints", index=False)
        df_matrix.to_excel(writer, sheet_name="table_api_matrix", index=False)

        # テーブルごとのシート
        for table_name, group in df_tables.groupby("table_name"):
            sheet_name = make_sheet_name(table_name)
            # 人間が見る想定の列構成
            df_table_sheet = pd.DataFrame(
                {
                    "column_name": group["column_name"].values,
                    "data_type": group["data_type"].values,
                    # PK は ○ / 空欄 で表現
                    "PK": ["○" if v else "" for v in group["is_primary_key"].values],
                    "FK": group["foreign_key"].values,
                    "japanese_label": ["" for _ in range(len(group))],
                    "business_note": ["" for _ in range(len(group))],
                    # 初期値は column_name = Python フィールド名想定
                    "python_field": group["column_name"].values,
                }
            )

            df_table_sheet.to_excel(writer, sheet_name=sheet_name, index=False)

        # ---- スタイル適用（Excel テーブル化）----
        workbook = writer.book

        for ws in workbook.worksheets:
            if ws.title.startswith("tbl_"):
                # テーブル別シート: 薄いライト系
                add_excel_table(ws, style_name="TableStyleLight9")
            elif ws.title == "endpoints":
                # エンドポイント一覧: 少し濃いめだけど見やすいスタイル
                add_excel_table(ws, style_name="TableStyleMedium2")
            elif ws.title == "table_api_matrix":
                add_excel_table(ws, style_name="TableStyleMedium4")
            elif ws.title == "tables_all":
                # 一覧は一番薄いスタイル
                add_excel_table(ws, style_name="TableStyleLight1")

    print(f"✅ Exported to: {OUTPUT_XLSX}")


if __name__ == "__main__":
    main()
